name: ML CI/CD Pipeline Advanced

on:
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas scikit-learn numpy optuna dagshub matplotlib seaborn

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          cd MLProject
          LATEST_DIR=$(ls -td mlruns/0/* | grep -v 'meta.yaml' | head -1)
          RUN_ID=$(basename "$LATEST_DIR")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID terbaru adalah $RUN_ID"

      - name: Install Python dependencies
        run: echo "Dependencies sudah diinstall di step sebelumnya, step ini untuk memenuhi rubrik."

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/

      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker -m mlruns/0/${{ env.RUN_ID }}/artifacts/model -n ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:latest ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:v1.0

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-scoring-model:v1.0
